export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LOGIN_GG_REQUEST = "USER_LOGIN_GG_REQUEST";
export const USER_LOGIN_GG_SUCCESS = "USER_LOGIN_GG_SUCCESS";
export const USER_LOGIN_GG_FAIL = "USER_LOGIN_GG_FAIL";
export const USER_GG_LOGOUT = "USER_GG_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET"

export const USER_CONFIRM_REGISTER_REQUEST = "USER_CONFIRM_REGISTER_REQUEST";
export const USER_CONFIRM_REGISTER_SUCCESS = "USER_CONFIRM_REGISTER_SUCCESS";
export const USER_CONFIRM_REGISTER_FAIL = "USER_CONFIRM_REGISTER_FAIL";
export const USER_CONFIRM_REGISTER_RESET = "USER_CONFIRM_REGISTER_RESET"

export const USER_FORGOT_REQUEST = "USER_FORGOT_REQUEST";
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS";
export const USER_FORGOT_FAIL = "USER_FORGOT_FAIL";
export const USER_FORGOT_RESET = "USER_FORGOT_RESET"

export const USER_CONFIRM_FORGOT_REQUEST = "USER_CONFIRM_FORGOT_REQUEST";
export const USER_CONFIRM_FORGOT_SUCCESS = "USER_CONFIRM_FORGOT_SUCCESS";
export const USER_CONFIRM_FORGOT_FAIL = "USER_CONFIRM_FORGOT_FAIL";
export const USER_CONFIRM_FORGOT_RESET = "USER_CONFIRM_FORGOT_RESET"

export const USER_CHANGE_REQUEST = "USER_CHANGE_REQUEST";
export const USER_CHANGE_SUCCESS = "USER_CHANGE_SUCCESS";
export const USER_CHANGE_FAIL = "USER_CHANGE_FAIL";
export const USER_CHANGE_RESET = "USER_CHANGE_RESET"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";
